DVhost/urls.py
"""
Definition of urls for DVhost.
"""

from datetime import datetime
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('feedback/', views.feedback, name='feedback'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Вход',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('registration/', views.registration, name='registration'),
    path('admin/', admin.site.urls),
    url(r'^(?P<parametr>\d+)/$', views.blogpost, name='blogpost'),
    path('newpost/', views.newpost, name='newpost'),
    path('videopost/', views.videopost, name='videopost'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _

from django.db import models
from .models import Comment
from .models import Blog

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'style': 'width: 100%;',
                                   'placeholder': 'Логин'}))
    password = forms.CharField(label=_("Пароль"),
                               widget=forms.PasswordInput({
                                   'style': 'width: 100%;',
                                   'placeholder':'Пароль'}))

class FeedbackForm(forms.Form):
    name = forms.CharField(label='Ваше имя', min_length=2, max_length=20)
    email = forms.EmailField(label='E-mail', min_length=7)
    direction = forms.ChoiceField(label='Обращение к', 
                                  choices=[
                                      ('1', 'Поддержка'), 
                                      ('2', 'Маркетинг')
                                      ], widget=forms.RadioSelect, initial=1)
    topic = forms.ChoiceField(label='Тема обращения', choices=(('1', 'Не удается загрузить файл'),
                                                        ('2', 'Удалить аккаунт'),
                                                        ('3', 'Изменить описания файла'),
                                                        ('4', 'Другое')), initial=1)
    check = forms.BooleanField(label='Имеется аккаунт', required=False)
    info = forms.CharField(label='Текст обращения', widget=forms.Textarea(attrs={'rows':4, 'cols':30}))

class CommentForm (forms.ModelForm):
    class Meta:
        model = Comment # используемая модель
        fields = ('text',) # требуется заполнить только поле text
        labels = {'text': "Комментарий"} # метка к полю формы text

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'description', 'content', 'file',)
        labels = {'title': "Имя файла", 'description': "Расширение", 'content': "Описание", 'file': "Файл"}

app/templates/app/about.html
{% extends "app/layout.html" %}
{% block content %}
<h2>О сервисе PigeonHost.ru.</h2>
Наш сайт призван предоставить пользователям нормальный качественный и в то же время простой сервис по размещению файлов в Сети.
<br><br>
Сервис PigeonHost.ru предоставляет вам возможность совершенно бесплатно размещать ваши файлы в интернете для других пользователей.
Наш сервис подойдёт вам для таких задач как: выложить картинки, изображения, скриншоты, фото или видео; отправить большие файлы; сохранить свои файлы в интернете.
<br><br>
В интернете существует огромная масса всевозможных файлообменных сервисов, но все они нацелены на выкачивание из пользователей денег: намеренно ограничивают скорость, показывают тонны рекламы, ограничивают максимальный размер файла, вынуждая разрезать большие файлы на части, настаивают на приобретении платных аккаунтов, проводят пользователей по десяткам промежуточных страниц, заставляют ждать некоторое время перед началом загрузки файлов.
<br><br>
На нашем сайте ничего такого нет. Всё честно: никаких искусственных ограничений, нет дополнительных окон с рекламой. Не требуется регистрации. Срок хранения файлов - неограничен. В дополнение ко всему, мы предоставляем прямые ссылки на файлы! И всё это - бесплатно. То есть - для людей.
{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}

{% block content %}

<h2> {{post_1.title}} </h2> <a href="/" style="float: right; margin-top: -50px;">Назад</a>
<div class="postMY">
    <ul>
        <li><div class="titlePost">Автор: </div><div class="dataPost">{{post_1.author}}</div></li>
        <li><div class="titlePost">Формат: </div><div class="dataPost">{{post_1.description}}</div></li>
        <li><div class="titlePost">Описание: </div><div class="dataPost">{{post_1.content|linebreaksbr}}</div></li>
    </ul>   
    <div class="postDown"><a href="{{ post_1.file.url }}" class="btn btn-info d-none d-md-inline-block">Сохранить файл {{ post_1.file.name }} на диск ({{ post_1.file.size|filesizeformat }})</a></div>
</div>
<hr>

{% if user.is_authenticated %}
<spavn class="comSpavn">Добавить комментарий:</spavn>
<form method="POST" class="comForm commform">{% csrf_token %} {# защита от атак CSRF#}
    <div>
        {{form.as_p}}
        <button type="submit" class="save btn btn-success" style="float: right;"> Отправить </button>
    </div>
</form>
{% else %}
<h3> Для добавления своего комментария, пожалуйста, авторизуйтесь </h3>
{% endif %}
{% if comment.count %}
-----
{% endif %}
<hr/>
{% for comment in comments %}
<div class="comm">
    <span class="comName">{{comment.author}}</span>
    <spavn class="comDate">{{comment.date}}</spavn>
    <div class="comText"> {{comment.text|linebreaksbr}} </div>
</div>
{% endfor %}

{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}
{% block content %}
<h2>Наши контакты.</h2>
<address>
    <strong>Поддержка:</strong><a href="mailto:Support@pigeonhost.ru"> Support@pigeonhost.ru</a><br/>
    <strong>Маркетинг:</strong><a href="mailto:Marketing@pigeonhost.ru"> Marketing@pigeonhost.ru</a>
</address>
{% endblock %}

app/templates/app/feedback.html
{% extends "app/layout.html" %}
{% block content %}
{% if form != None %}
<h2>Обратная связь.</h2>
<div>
    <form method="post" class="feedback" id="feedback">
        {% csrf_token %}
        <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
        {{ form.name }}<br>
        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
        {{ form.email }}<br>
        <label for="{{ form.direction.id_for_label }}">{{ form.direction.label }}:</label>
        {{ form.direction }}<br>
        <label for="{{ form.topic.id_for_label }}">{{ form.topic.label }}:</label>
        <div class="select">{{ form.topic }}</div><br>
        <label for="{{ form.check.id_for_label }}">{{ form.check.label }}?</label>
        {{ form.check }}<br>
        <label for="{{ form.info.id_for_label }}">{{ form.info.label }}:</label>
        {{ form.info }}<br>
        <div><input type="submit" value="Отправить" id="btn"></div>
    </form>
</div>
{% else %}
<br>
<h1>Ваше обращение отправлено!</h1>
<br>
<h1 style="font-size: 20px;">Текст обращения:</h1>
<ul>
    <li><span>Имя: </span>{{ data.name }}</li>
    <li><span>E-mail: </span>{{ data.email }}</li>
    <li><span>Обращение к: </span>{{ data.direction }}</li>
    <li><span>Тема обращения: </span>{{ data.topic }}</li>
    <li><span>Наличие аккаунта: </span>{{ data.check }}</li>
    <li><span>Текст обращения: </span>{{ data.info }}</li>
</ul>
{% endif %}

            <script>
                function focus_input(nam)
                {
                    $(nam).css('background-color', 'red');
                }
                function blur_input(nam)
                {
                    $(nam).css('background-color', 'yellow');
                }
                

                $('#id_name').css('background-color', 'yellow');
                $('#id_name').focus(function() { focus_input('#id_name') });
                $('#id_name').blur(function () { blur_input('#id_name') });

                $('#id_email').css('background-color', 'yellow');
                $('#id_email').focus(function() { focus_input('#id_email') });
                $('#id_email').blur(function() { blur_input('#id_email') });

                
                $('#id_topic').css('background-color', 'yellow');
                $('#id_topic').focus(function() { focus_input('#id_topic') });
                $('#id_topic').blur(function () { blur_input('#id_topic') });

                $('#id_info').css('background-color', 'yellow');
                $('#id_info').focus(function() { focus_input('#id_info') });
                $('#id_info').blur(function () { blur_input('#id_info') });

                $('#btn').css({ 'background-color': 'yellow', 'color': '#d1d1d1'});
                $('#btn').mouseover(function() {  $('#btn').css({ 'background-color': 'red', 'color': '#000000'}); });
                $('#btn').mouseout(function () { $('#btn').css({ 'background-color': 'yellow', 'color': '#d1d1d1'}); });
            </script>
{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}
{% load staticfiles %}
{% block content %}
<div class="table-name">
    <div class="table-heading">
        <h1>Последние файлы</h1>
    </div>
    <div class="table-search">
        <div class="input-search"><svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M10.4834 9.18645L10.2381 9.53097L10.5371 9.83005L14.3535 13.6465C14.5488 13.8417 14.5488 14.1583 14.3535 14.3535C14.1583 14.5488 13.8417 14.5488 13.6465 14.3535L9.83005 10.5371L9.53097 10.2381L9.18645 10.4834C8.28755 11.1236 7.18845 11.5 6 11.5C2.96243 11.5 0.5 9.03756 0.5 6C0.5 2.96243 2.96243 0.5 6 0.5C9.03756 0.5 11.5 2.96243 11.5 6C11.5 7.18845 11.1236 8.28755 10.4834 9.18645ZM6 1.5C3.51472 1.5 1.5 3.51472 1.5 6C1.5 8.48524 3.51471 10.5 6 10.5C8.48524 10.5 10.5 8.48524 10.5 6C10.5 3.51471 8.48524 1.5 6 1.5Z" fill="#2C2C2C" stroke="#2C2C2C"/></svg></div>
        <input type="text" placeholder="Введите название"/>
    </div>
</div>
<div class="table-block">
    <table>
        <tr><th>Имя</th><th>Тип</th><th>Дата загрузки</th><th></th></tr> 
        {% for post in posts %}
        <tr>
            <td class="td-name">
                <div>{{post.title}}</div>
            </td>
            <td class="td-type">
                {{post.description}}
            </td>
            <td class="td-date">
                {{post.posted}}
            </td>
            <td href="vk.con" style="width: 48px;">
                <a href="{% url 'blogpost' parametr=post.id %}">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M6 14C7.10457 14 8 13.1046 8 12C8 10.8954 7.10457 10 6 10C4.89543 10 4 10.8954 4 12C4 13.1046 4.89543 14 6 14ZM12 14C13.1046 14 14 13.1046 14 12C14 10.8954 13.1046 10 12 10C10.8954 10 10 10.8954 10 12C10 13.1046 10.8954 14 12 14ZM20 12C20 13.1046 19.1046 14 18 14C16.8954 14 16 13.1046 16 12C16 10.8954 16.8954 10 18 10C19.1046 10 20 10.8954 20 12Z" fill="#E0E0E0"/></svg>
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
    
</div>
<div class="table-nav">
    <div class="table-nav-left">
        Всего файлов: 
        <a>{{postCount}}</a>
    </div>
    <div class="table-nav-right">
        {% if posts.has_previous %}
        <a href="?page={{ posts.previous_page_number }}" class="">«</a>
         {% endif %}
        {% if posts.has_previous or posts.has_next %}
        <a class="table-nav-activ">{{ posts.number }}</a>
        {% endif %}
        {% if posts.has_next %}
        <a href="?page={{ posts.next_page_number }}" style="margin: 0;">»</a>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PigeonHost</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>

    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>

</head>

<body>
{% load staticfiles %}
    <div class="navbar-new navbar navbar-inverse navbar-fixed-top ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"> <img src="{% static 'app/content/images/logo.png' %}" alt="PigeonHost" class="logo"/> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'feedback' %}">Обратная связь</a></li>
                    <li><a href="{% url 'newpost' %}">Добавить файл</a></li>
                    <li><a href="{% url 'videopost' %}">Видео</a></li>
                </ul>

                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>
            <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000" style="width: 500px; margin: 0 auto 30px auto;">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active darkened">
                    <img src="{% static 'app/content/1.jpg'%} " alt="Первый слайд" class="img-responsive" />
                    <div class="carousel-caption" role="option">
                        <p>
                            Хостинг-провайдер Managed.com отключил серверы из-за атаки вымогателя
                            <a class="btn btn-default" href="https://www.anti-malware.ru/news/2020-11-18-114534/34269">
                                Читать далее
                            </a>
                        </p>
                    </div>
                </div>
                <div class="item darkened">
                    <img src="{% static 'app/content/2.jpg'%}" alt="Второй слайд"  class="img-responsive" />
                    <div class="carousel-caption" role="option">
                        <p>
                            Что такое безлимитный хостинг сайтов?
                            <a class="btn btn-default" href="https://from-ua.com/news/574859-chto-takoe-bezlimitnii-hosting-saitov.html">
                                Читать далее
                            </a>
                        </p>
                    </div>
                </div>
                <div class="item darkened">
                    <img src=" {% static 'app/content/3.jpg'%} " alt="Третий слайд"  class="img-responsive" />
                    <div class="carousel-caption" role="option">
                        <p>
                            Asus представила сервер высокой плотности 2U для шести узлов на процессорах EPYC 7002<br>
                            <a class="btn btn-default" href="https://www.cnews.ru/news/line/2020-11-17_asus_predstavila_server_vysokoj">
                                Читать далее
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev" style="z-index:2;">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next" style="z-index:2;">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <div class="social-ico">
                <a href ="https://facebook.com/PigeonHost" target="_blank"> <img src="{% static 'app/content/images/facebook.png' %}" alt="facebok" title="facebok.com"/></a>
                <a href ="https://twitter.com/PigeonHost" target="_blank"> <img src="{% static 'app/content/images/twitter.png' %}" alt="twitter" title="twitter.com"/></a>
                <a href ="https://vk.com/PigeonHost" target="_blank"> <img src="{% static 'app/content/images/vk.png' %}" alt="vk" title="vk.com"/></a>
            </div>
            <p>2020 &copy; <a href="/">PigeonHost</a></p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используйте локальную учетную запись для входа в систему.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Логин:</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль:</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйста, введите правильное имя пользователя и пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right" style="margin: 0;">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">{{ user.username }}</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()" style="padding-right: 0;">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'registration' %}">Регистрация</a></li>
    <li><a href="{% url 'login' %}" style="padding-right: 0;">Войти</a></li>
</ul>

{% endif %}

app/templates/app/newpost.html
{% extends "app/layout.html" %}

{% block content %}
<h3>Добавление файла</h3><br>
<form method="POST" enctype="multipart/form-data" class="formpostnew">{% csrf_token %} {# защита от атак CSRF#}
    <div>
        {{ blogform.as_p }}
        <button type="submit" class="save btn btn-success" style="float: right;"> Отправить </button>
    </div>
</form>


{% endblock %}

app/templates/app/registration.html
{% extends "app/layout.html" %}

{% block content %}

<h2>Регистрация пользователя</h2>

<form method="POST" class="regForm"> {% csrf_token %}

<div>

{{ regform.as_p}}

<button type="submit" class="save btn btn-default" > Зарегистрировать </button>

</div>

</form>

{% endblock %}

app/templates/app/videopost.html
{% extends "app/layout.html" %}

{% block content %}
<h1>Что такое хостинг, домен и как устроен интернет на понятном языке</h1><br>
<div style="    width: 560px;    margin: auto;">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/v80A1i-82CE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<h1>Что такое хостинг и для чего он нужен – простыми словами</h1><br>
<div style="    width: 560px;    margin: auto;">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/2bBCSyvkA4M" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

{% endblock %}